<?php
/**
 * GitHub-based plugin updater.
 *
 * How it works:
 * 1. WordPress runs `pre_set_site_transient_update_plugins` on its update schedule.
 *    We inject our update info if a newer GitHub Release exists.
 * 2. WordPress renders "View details" popup via `plugins_api`. We provide info.
 * 3. When user clicks "Update", WP downloads the zip, extracts it, and tries
 *    to copy into `wp-content/plugins/digitone-events/`. GitHub archives extract
 *    to `<repo>-<version>/` so we rename via `upgrader_source_selection`.
 *
 * Release detection:
 * - Reads the LATEST GitHub Release of the configured repo.
 * - Prefers a release asset named "digitone-events*.zip" (built by our workflow).
 * - Falls back to the auto-generated zipball_url if no asset is found.
 *
 * Configuration:
 * - Owner/repo: define constants in wp-config.php OR set in Settings page.
 * - Private repo token: define( 'DIGITONE_EVENTS_GH_TOKEN', '...' ) preferred,
 *   or set in Settings (stored in wp_options).
 *
 * @package DigitOne_Events
 */

defined( 'ABSPATH' ) || exit;

final class DigitOne_Events_Github_Updater {

	private const TRANSIENT_KEY     = 'digitone_events_gh_release';
	private const TRANSIENT_TTL     = 6 * HOUR_IN_SECONDS;
	private const OPTION_OWNER      = 'digitone_events_gh_owner';
	private const OPTION_REPO       = 'digitone_events_gh_repo';
	private const OPTION_TOKEN      = 'digitone_events_gh_token';

	public function register() : void {
		add_filter( 'pre_set_site_transient_update_plugins', [ $this, 'inject_update' ] );
		add_filter( 'plugins_api', [ $this, 'plugins_api' ], 20, 3 );
		add_filter( 'upgrader_source_selection', [ $this, 'rename_source' ], 10, 4 );
		add_action( 'upgrader_process_complete', [ $this, 'on_upgrade_complete' ], 10, 2 );

		// Force-check AJAX endpoint (clears cache and refetches).
		add_action( 'wp_ajax_digitone_events_check_update', [ $this, 'ajax_force_check' ] );
	}

	/* ============================================================
	 * Configuration accessors
	 * ============================================================ */

	public function owner() : string {
		$opt = get_option( self::OPTION_OWNER );
		return $opt ? (string) $opt : DIGITONE_EVENTS_GH_OWNER;
	}

	public function repo() : string {
		$opt = get_option( self::OPTION_REPO );
		return $opt ? (string) $opt : DIGITONE_EVENTS_GH_REPO;
	}

	public function token() : string {
		// Constant wins (more secure).
		if ( defined( 'DIGITONE_EVENTS_GH_TOKEN' ) && DIGITONE_EVENTS_GH_TOKEN ) {
			return (string) DIGITONE_EVENTS_GH_TOKEN;
		}
		$opt = get_option( self::OPTION_TOKEN );
		return $opt ? (string) $opt : '';
	}

	/* ============================================================
	 * Release detection
	 * ============================================================ */

	/**
	 * @return array|null { version, zip_url, body, html_url, published_at, asset_size }
	 */
	public function get_latest_release( bool $force = false ) : ?array {
		if ( ! $force ) {
			$cached = get_transient( self::TRANSIENT_KEY );
			if ( is_array( $cached ) ) {
				return $cached;
			}
		}

		$owner = $this->owner();
		$repo  = $this->repo();
		if ( ! $owner || ! $repo ) {
			return null;
		}

		$url  = "https://api.github.com/repos/{$owner}/{$repo}/releases/latest";
		$args = [
			'timeout' => 15,
			'headers' => [
				'Accept'     => 'application/vnd.github+json',
				'User-Agent' => 'DigitOne-Events-Updater',
			],
		];
		$token = $this->token();
		if ( $token ) {
			$args['headers']['Authorization'] = 'Bearer ' . $token;
		}

		$response = wp_remote_get( $url, $args );
		if ( is_wp_error( $response ) ) {
			// Cache a negative result briefly to avoid hammering API on failure.
			set_transient( self::TRANSIENT_KEY, [], MINUTE_IN_SECONDS * 15 );
			return null;
		}

		$code = wp_remote_retrieve_response_code( $response );
		if ( $code !== 200 ) {
			set_transient( self::TRANSIENT_KEY, [], MINUTE_IN_SECONDS * 15 );
			return null;
		}

		$data = json_decode( wp_remote_retrieve_body( $response ), true );
		if ( ! is_array( $data ) || empty( $data['tag_name'] ) ) {
			return null;
		}

		// Normalize tag like "v0.1.0" -> "0.1.0".
		$version = ltrim( (string) $data['tag_name'], 'vV' );

		// Prefer release asset that matches our plugin slug.
		$zip_url    = '';
		$asset_size = 0;
		if ( ! empty( $data['assets'] ) && is_array( $data['assets'] ) ) {
			foreach ( $data['assets'] as $asset ) {
				if ( empty( $asset['name'] ) || empty( $asset['browser_download_url'] ) ) {
					continue;
				}
				if ( stripos( $asset['name'], DIGITONE_EVENTS_SLUG ) === 0 && substr( $asset['name'], -4 ) === '.zip' ) {
					$zip_url    = (string) $asset['browser_download_url'];
					$asset_size = isset( $asset['size'] ) ? (int) $asset['size'] : 0;
					break;
				}
			}
		}
		// Fallback to autogenerated zipball.
		if ( ! $zip_url && ! empty( $data['zipball_url'] ) ) {
			$zip_url = (string) $data['zipball_url'];
		}

		$result = [
			'version'      => $version,
			'zip_url'      => $zip_url,
			'body'         => isset( $data['body'] ) ? (string) $data['body'] : '',
			'html_url'     => isset( $data['html_url'] ) ? (string) $data['html_url'] : '',
			'published_at' => isset( $data['published_at'] ) ? (string) $data['published_at'] : '',
			'asset_size'   => $asset_size,
		];

		set_transient( self::TRANSIENT_KEY, $result, self::TRANSIENT_TTL );
		return $result;
	}

	/* ============================================================
	 * WordPress update injection
	 * ============================================================ */

	public function inject_update( $transient ) {
		if ( empty( $transient ) || ! is_object( $transient ) ) {
			return $transient;
		}
		if ( empty( $transient->checked ) ) {
			return $transient;
		}

		$release = $this->get_latest_release();
		if ( ! $release || empty( $release['version'] ) || empty( $release['zip_url'] ) ) {
			return $transient;
		}

		if ( version_compare( $release['version'], DIGITONE_EVENTS_VERSION, '<=' ) ) {
			return $transient;
		}

		$plugin = (object) [
			'id'            => DIGITONE_EVENTS_BASENAME,
			'slug'          => DIGITONE_EVENTS_SLUG,
			'plugin'        => DIGITONE_EVENTS_BASENAME,
			'new_version'   => $release['version'],
			'url'           => $release['html_url'] ?: "https://github.com/{$this->owner()}/{$this->repo()}",
			'package'       => $this->signed_package_url( $release['zip_url'] ),
			'icons'         => [],
			'banners'       => [],
			'banners_rtl'   => [],
			'tested'        => get_bloginfo( 'version' ),
			'requires_php'  => '8.0',
			'compatibility' => new stdClass(),
		];

		$transient->response[ DIGITONE_EVENTS_BASENAME ] = $plugin;
		return $transient;
	}

	/**
	 * For private repos, append the token so wp_remote_get inside the Upgrader
	 * can download the asset. For public repos, return URL unchanged.
	 *
	 * Note: GitHub release-asset download URLs from a private repo require an
	 * Accept: application/octet-stream header — which WP_Upgrader_Skin sends
	 * via Authorization. We use 'http_request_args' filter to add it.
	 */
	private function signed_package_url( string $url ) : string {
		if ( $this->token() ) {
			add_filter( 'http_request_args', [ $this, 'add_auth_header_to_download' ], 10, 2 );
		}
		return $url;
	}

	public function add_auth_header_to_download( $args, $url ) {
		// Only attach to GitHub release downloads.
		if ( strpos( (string) $url, 'github.com' ) === false && strpos( (string) $url, 'githubusercontent.com' ) === false ) {
			return $args;
		}
		$token = $this->token();
		if ( ! $token ) {
			return $args;
		}
		if ( ! isset( $args['headers'] ) || ! is_array( $args['headers'] ) ) {
			$args['headers'] = [];
		}
		$args['headers']['Authorization'] = 'Bearer ' . $token;
		// For release assets, GitHub needs this Accept header.
		$args['headers']['Accept'] = 'application/octet-stream';
		return $args;
	}

	/* ============================================================
	 * "View details" popup
	 * ============================================================ */

	public function plugins_api( $result, $action, $args ) {
		if ( $action !== 'plugin_information' ) {
			return $result;
		}
		if ( empty( $args->slug ) || $args->slug !== DIGITONE_EVENTS_SLUG ) {
			return $result;
		}

		$release = $this->get_latest_release();
		if ( ! $release ) {
			return $result;
		}

		$info = (object) [
			'name'           => 'DigitOne Events',
			'slug'           => DIGITONE_EVENTS_SLUG,
			'version'        => $release['version'],
			'author'         => '<a href="https://github.com/' . esc_attr( $this->owner() ) . '">DIGIT</a>',
			'homepage'       => $release['html_url'] ?: "https://github.com/{$this->owner()}/{$this->repo()}",
			'requires'       => '6.4',
			'requires_php'   => '8.0',
			'tested'         => get_bloginfo( 'version' ),
			'last_updated'   => $release['published_at'] ?: '',
			'download_link'  => $release['zip_url'],
			'trunk'          => $release['zip_url'],
			'sections'       => [
				'description' => 'Conference & event management with multi-event backend, sessions, speakers, venues, days, and frontend shortcodes.',
				'changelog'   => $this->markdown_lite( $release['body'] ),
			],
			'banners'        => [],
		];
		return $info;
	}

	/* ============================================================
	 * Rename extracted folder to match plugin slug
	 * ============================================================ */

	public function rename_source( $source, $remote_source, $upgrader, $hook_extra = [] ) {
		// Only act on our plugin updates.
		if ( ! isset( $hook_extra['plugin'] ) || $hook_extra['plugin'] !== DIGITONE_EVENTS_BASENAME ) {
			return $source;
		}
		if ( ! is_string( $source ) || $source === '' ) {
			return $source;
		}

		global $wp_filesystem;
		$expected = trailingslashit( $remote_source ) . DIGITONE_EVENTS_SLUG;
		$current  = untrailingslashit( $source );

		if ( $current === untrailingslashit( $expected ) ) {
			return $source;
		}

		if ( $wp_filesystem && $wp_filesystem->move( $current, $expected, true ) ) {
			return trailingslashit( $expected );
		}

		return $source; // Let WP handle / fail normally.
	}

	/* ============================================================
	 * Post-upgrade cleanup
	 * ============================================================ */

	public function on_upgrade_complete( $upgrader, $hook_extra ) {
		if ( ! is_array( $hook_extra ) ) {
			return;
		}
		if ( ( $hook_extra['action'] ?? '' ) !== 'update' ) {
			return;
		}
		if ( ( $hook_extra['type'] ?? '' ) !== 'plugin' ) {
			return;
		}
		if ( empty( $hook_extra['plugins'] ) || ! in_array( DIGITONE_EVENTS_BASENAME, (array) $hook_extra['plugins'], true ) ) {
			return;
		}

		// Clear our own GitHub release cache AND the WP-level update_plugins
		// transient. Without clearing the latter, WP keeps the stale "update
		// available" row from before the upgrade, causing the user to have to
		// click Update twice before the banner clears.
		delete_transient( self::TRANSIENT_KEY );
		delete_site_transient( 'update_plugins' );
	}

	/* ============================================================
	 * Force-check endpoint (Settings page button)
	 * ============================================================ */

	public function ajax_force_check() : void {
		DigitOne_Events_Security_Nonce::verify_ajax();

		delete_transient( self::TRANSIENT_KEY );
		delete_site_transient( 'update_plugins' );
		$release = $this->get_latest_release( true );

		if ( ! $release ) {
			wp_send_json_error( [ 'message' => __( 'Could not reach GitHub or no releases found.', 'digitone-events' ) ] );
		}

		$is_newer   = version_compare( $release['version'], DIGITONE_EVENTS_VERSION, '>' );
		$update_url = '';
		if ( $is_newer ) {
			// Direct deep-link to WP's plugin update screen — clicking starts the update immediately.
			$update_url = wp_nonce_url(
				self_admin_url( 'update.php?action=upgrade-plugin&plugin=' . urlencode( DIGITONE_EVENTS_BASENAME ) ),
				'upgrade-plugin_' . DIGITONE_EVENTS_BASENAME
			);
		}

		wp_send_json_success( [
			'latest'     => $release['version'],
			'installed'  => DIGITONE_EVENTS_VERSION,
			'is_newer'   => $is_newer,
			'html_url'   => $release['html_url'],
			'zip_url'    => $release['zip_url'],
			'update_url' => $update_url,
		] );
	}

	/* ============================================================
	 * Tiny Markdown -> HTML for changelog body
	 * ============================================================ */

	private function markdown_lite( string $md ) : string {
		$md = trim( $md );
		if ( $md === '' ) {
			return '';
		}

		$html = esc_html( $md );

		// Headings
		$html = preg_replace( '/^### (.+)$/m', '<h4>$1</h4>', $html );
		$html = preg_replace( '/^## (.+)$/m', '<h3>$1</h3>', $html );
		$html = preg_replace( '/^# (.+)$/m', '<h2>$1</h2>', $html );

		// Bold / italic
		$html = preg_replace( '/\*\*(.+?)\*\*/', '<strong>$1</strong>', $html );
		$html = preg_replace( '/(?<!\*)\*(?!\*)(.+?)(?<!\*)\*(?!\*)/', '<em>$1</em>', $html );

		// Bullet lists
		$html = preg_replace( '/^- (.+)$/m', '<li>$1</li>', $html );
		$html = preg_replace( '/(<li>.*?<\/li>\s*)+/s', '<ul>$0</ul>', $html );

		// Line breaks
		$html = nl2br( $html );

		return $html;
	}
}
